[project]
name = "cloudconvertheic"
version = "1.0.0"
description = "Convert all heic files in a directory to jpg format using the CloudConvert REST API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cloudconvert>=2.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
